version: 0.1.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
build:
  project: etc/visual-studio/openthread.sln
  verbosity: minimal
test: off