version: 0.1.{build}
image: Previous Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
build:
  project: openthread.sln
  verbosity: minimal
test_script:
- cmd: >-
    set Platform2=%Platform%

    if %Platform2%==x86 set Platform2=Win32

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /platform:%Platform% build\bin\%Platform2%\%Configuration%\dll\UnitTests.dll