version: 0.1.{build}
image: Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
install:
- ps: >-
    Bcdedit.exe -set TESTSIGNING ON

    Restart-Computer -Force

    Start-Sleep -s 10
build:
  project: etc/visual-studio/openthread.sln
  verbosity: minimal
after_build:
- cmd: >-
    set Platform2=%Platform%

    if %Platform2%==x86 set Platform2=Win32

    mkdir release

    copy build\bin\%Platform2%\%Configuration%\sys\otlwf\* release

    copy build\bin\%Platform2%\%Configuration%\sys\otlwf.cer release

    copy build\bin\%Platform2%\%Configuration%\dll\otApi.dll release

    copy build\bin\%Platform2%\%Configuration%\dll\otApi.pdb release

    copy build\bin\%Platform2%\%Configuration%\exe\otCli.exe release

    copy build\bin\%Platform2%\%Configuration%\exe\otCli.pdb release

    mkdir test_release

    copy build\bin\%Platform2%\%Configuration%\dll\ot*.dll test_release

    copy build\bin\%Platform2%\%Configuration%\dll\ot*.pdb test_release

    copy build\bin\%Platform2%\%Configuration%\exe\otTestRunner.* test_release
test_script:
- cmd: >-
    vstest.console /logger:Appveyor /inIsolation /platform:%Platform% build\bin\%Platform2%\%Configuration%\dll\UnitTests.dll

    cd build\bin\%Platform2%\%Configuration%\sys

    certutil -addstore root otLwf.cer

    certutil -addstore TrustedPublisher otLwf.cer

    cd otLwf

    netcfg.exe -v -l otlwf.inf -c s -i otLwf

    Sleep 5

    sc query otlwf

    cd ..\..\..\..\..\..\test_release
artifacts:
- path: release
  name: release