version: 0.1.{build}
image: Visual Studio 2015
configuration:
- Release
- Debug
platform:
- x64
- x86
clone_depth: 10
install:
- ps: >-
    Bcdedit.exe -set TESTSIGNING ON

    Restart-Computer -Force

    Start-Sleep -s 10
build:
  project: etc/visual-studio/openthread.sln
  verbosity: minimal
after_build:
- ps: >-
    $env:Platform2 = $env:Platform

    If ($env:Platform2 -eq "x86") s$env:Platform2 = "Win32""

    mkdir release

    copy build\bin\$env:Platform2\$env:Configuration\sys\otlwf\* release

    copy build\bin\$env:Platform2\$env:Configuration\sys\otlwf.cer release

    copy build\bin\$env:Platform2\$env:Configuration\dll\otApi.dll release

    copy build\bin\$env:Platform2\$env:Configuration\dll\otApi.pdb release

    copy build\bin\$env:Platform2\$env:Configuration\exe\otCli.exe release

    copy build\bin\$env:Platform2\$env:Configuration\exe\otCli.pdb release

    mkdir test_release

    copy build\bin\$env:Platform2\$env:Configuration\dll\ot*.dll test_release

    copy build\bin\$env:Platform2\$env:Configuration\dll\ot*.pdb test_release

    copy build\bin\$env:Platform2\$env:Configuration\exe\otTestRunner.* test_release

    cd build\bin\$env:Platform2\$env:Configuration\sys

    certutil -addstore root otLwf.cer

    certutil -addstore TrustedPublisher otLwf.cer

    cd otLwf

    netcfg.exe -v -l otlwf.inf -c s -i otLwf

    cd ..\..\..\..\..\..

    Restart-Computer -Force

    Start-Sleep -s 10
test_script:
- cmd: >-
    vstest.console /logger:Appveyor /inIsolation /platform:%Platform% build\bin\%Platform2%\%Configuration%\dll\UnitTests.dll

    sc query otlwf

    cd test_release

    otTestRunner.exe ..\tests\scripts\thread-cert Test_otLwf* verbose appveyor
artifacts:
- path: release
  name: release